version: '3.4'

name: ngnix-stack

services:

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 5678:5678
      - 80:80 
    volumes:
      # - ./config/api-gateway.conf:/etc/nginx/conf.d/api-gateway.conf
      # - ./config/default.conf:/etc/nginx/conf.d/default.conf
      # - ./config/direct-api.conf:/etc/nginx/conf.d/direct-api.conf
      # - ./config/identity.conf:/etc/nginx/conf.d/identity.conf
      # - ./config/kibana.conf:/etc/nginx/conf.d/kibana.conf
      # - ./config/kong.conf:/etc/nginx/conf.d/kong.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/custom:/etc/nginx/conf.d/custom
      - ./log:/var/log/nginx
     
    # network_mode: host
    networks:    
      sample.ms.net: null
      internal.sample.ms.net:
          ipv4_address: 10.0.0.99
         
      
networks: 
  sample.ms.net:
    name: sample.ms.net   
    driver: bridge
  internal.sample.ms.net:
    name: internal.sample.ms.net
    external: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
        
    
  
