version: '3.4'

services:

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 5678:5678
      - 80:80 
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
     
    # network_mode: host
    networks:    
      sample.ms.net: null
      internal.sample.ms.net:
          ipv4_address: 10.0.0.99
         
      
networks: 
  sample.ms.net:
    driver: bridge
  internal.sample.ms.net:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
        
    
  
