version: '3.4'

name: apis-stack

services:
  sampleapi:
    image: ${DOCKER_REGISTRY-}sampleapi
    build:
      context: .
      dockerfile: Services/SampleApi/Dockerfile

  #sampleapi0:
  #  image: ${DOCKER_REGISTRY-}sampleapi
    

  sampleapi2:
    image: ${DOCKER_REGISTRY-}sampleapi2
    build:
      context: .
      dockerfile: Services/SampleApi2/Dockerfile

  samplesapi3:
    image: ${DOCKER_REGISTRY-}samplesapi3
    build:
      context: .
      dockerfile: Services/SamplesApi3/Dockerfile

  api3_postgresql:
    image: docker.io/bitnami/postgresql:16
    

