version: '3.4'

services:

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 5678:5678      
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      
   # network_mode: host
