version: '3.4'

name: apis-stack

services:
  sampleapi:
    image: ${DOCKER_REGISTRY-}sampleapi
    build:
      context: .
      dockerfile: Services/SampleApi/Dockerfile

  sampleapi2:
    image: ${DOCKER_REGISTRY-}sampleapi2
    build:
      context: .
      dockerfile: Services/SampleApi2/Dockerfile
  
 
 


