# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
- host: mockbin.org
  name: example_service
  port: 80
  protocol: http
  #plugins: 
  #- name: oidc
  #  config: 
  #    discovery: http://keyclok:8080/realms/sample-ms-jfb/.well-known/openid-configuration
  #    client_id: kong
  #    client_secret: bSJI3uuRZdFI8ebXGaKJxVmc2hJkkCrE
  routes:
  - name: example_route
    paths:
    - /mock
    strip_path: true