version: '3.4'

services: 
   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

   kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2   

volumes:  
  elasticsearch-data: