version: '3.4'

services:

  elastic.apm:
     container_name: elastic-apm
     image: elastic/apm-server:7.9.2
     environment:      
      - output.elasticsearch.hosts=["elasticsearch:9200"]
     depends_on:
      - elasticsearch
     #ports:
     # - "8200"
     networks:
      - elastic-apm--net
     volumes:
      - ./apm/config/apm-server.docker.yml:/usr/share/apm-server/apm-server.docker.yml   

networks:
    elastic-apm--net:
      name: internal.sample.ms.net
      external: true      