# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  openldap:
    container_name: opendldap
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USER_DC=users
      # - LDAP_ORGANISATION=example-org
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ROOT=dc=example,dc=org
      # - LDAP_RFC2307BIS_SCHEMA=true
      # - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      # - LDAP_TLS_VERIFY_CLIENT=never
    volumes:
      - 'openldap_data:/bitnami/openldap'
    networks:
      - openldap-net

  # ldap-ui:  
  #   container_name: ldap-ui
  #   image: osixia/phpldapadmin
  #   environment:
  #     - PHPLDAPADMIN_LDAP_HOSTS=openldap:1389
  #   networks:
  #     - openldap-net  
  #   ports:
  #     - 6443:443

  openldap-ui:
    image: wheelybird/ldap-user-manager:v1.5
    container_name: openldap-ui
    environment:
      - LDAP_URI=ldap://openldap
      - LDAP_BASE_DN=dc=example,dc=org
      - LDAP_REQUIRE_STARTTLS=FALSE
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=example,dc=org
      - LDAP_ADMIN_BIND_PWD=adminpassword
      - LDAP_IGNORE_CERT_ERRORS=true
      - NO_HTTPS=TRUE
      - PASSWORD_HASH=SSHA
      - SERVER_HOSTNAME=localhost:18080
    depends_on:
      - openldap
    ports:
      - 18080:80
    networks:
       - openldap-net


volumes:
  openldap_data:
    driver: local

networks:
    openldap-net:
      name: internal.sample.ms.net
      external: true